### ISSUE TITLE
Check HTML GitHub Action Invalid Option

### ISSUE THREAD

**Issue by trashutz** [swingconnection-leipzig/swingconnection#398]
`htmlproofer` is complaining about `check-favicon ` argument. 

Maybe it's deprecated? But repo didn't get any recent update.

```
Run chabad360/htmlproofer@master
  with:
    directory: ./public
    arguments: --only-4xx --check-favicon --check-html --assume-extension --empty-alt-ignore --disable-external
/usr/bin/docker run --name ghcriochabad360htmlproofer_6b2e0a --label 288919 --workdir /github/workspace --rm -e "INPUT_DIRECTORY" -e "INPUT_ARGUMENTS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoint.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/swingconnection/swingconnection":"/github/workspace" ghcr.io/chabad360/htmlproofer
5.0.7
/usr/local/bundle/gems/html-proofer-5.0.7/lib/html_proofer/configuration.rb:68:in `parse_cli_options': invalid option: --check-favicon (OptionParser::InvalidOption)
Did you mean?  check-sri
	from /usr/local/bundle/gems/html-proofer-5.0.7/lib/html_proofer/cli.rb:14:in `run'
	from /usr/local/bundle/gems/html-proofer-5.0.7/exe/htmlproofer:14:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
	from /usr/local/bundle/gems/html-proofer-5.0.7/exe/htmlproofer:14:in `<top (required)>'
	from /usr/local/bundle/bin/htmlproofer:25:in `load'
	from /usr/local/bundle/bin/htmlproofer:25:in `<main>'
```

**Comment by trashutz** [comment]
MR [!399](https://github.com/swingconnection-leipzig/swingconnection/pull/399) is fixing arguments, but now gets warning `HTML-Proofer found 1038 failures!`

Most of them -> internal [...] does not exist -> problem of finding images, links and files
